### ISSUE TITLE
Query by time?

### ISSUE THREAD

**Issue by cobbr2** [aws/aws-sdk-ruby-record#40]
It appears the attribute marshallers know about date-time, but the query stack does not.  What's the best workaround for now? I'd like to make sure I marshal exactly like the attribute mappers do, so it appears I should reach deeply into the Marshaler::DateTime class to get my value translated?

With a hash key of "data_source_id" and a sort key of "input_file_mtime", I try a query like:

Model:

```
   class Thang
     include Aws::Record
     set_table_name 'thangs'
     integer_attr :data_source_id, hash_key: true
     datetime_attr :input_file_mtime, sort_key: true
   end
```

Query:

```
         key_condition_expression:
           '#data_source_id = :data_source_id AND #input_file_mtime = :timestamp',
        expression_attribute_names: {
           '#data_source_id' => 'data_source_id',
           '#input_file_mtime' => 'input_file_mtime',
         },
         expression_attribute_values: {
           ':input_file_mtime' => opts[:input_file_mtime],
           ':data_source_id' => opts[:data_source_id],
         },
```

Result:

```
     ArgumentError:
       unsupported type, expected Hash, Array, Set, String, Numeric, IO, true, false, or nil, got Time
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/dynamodb/attribute_value.rb:47:in `format'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/dynamodb/attribute_value.rb:16:in `marshal'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:191:in `translate'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:185:in `block in map'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:184:in `each'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:184:in `with_object'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:184:in `map'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:201:in `translate_complex'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:193:in `translate'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:166:in `block in structure'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:165:in `each'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:165:in `with_object'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:165:in `structure'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:152:in `apply'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:121:in `translate_input'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/dynamodb_simple_attributes.rb:111:in `call'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/seahorse/client/plugins/response_target.rb:21:in `call'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/seahorse/client/request.rb:70:in `send_request'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-sdk-core-2.6.5/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-record-1.0.1/lib/aws-record/record/item_collection.rb:79:in `items'
     # /home/rcobb/.rvm/gems/ruby-2.1.5@stone/gems/aws-record-1.0.1/lib/aws-record/record/item_collection.rb:40:in `each'
```

**Comment by awood45** [comment]
This is, unfortunately, a current limitation of the query/scan interface. On the backlog is adding a higher-level query interface which would handle this, built on top of the low-level query interface.

Definitely open to feedback about what that would look like (we didn't hear much during the developer preview).

**Comment by IbottaBaier** [comment]
@cobbr2
You probably worked around this by now, if able... but my plan is to use an `integer_attr` and store seconds. Since `Time` and `DateTime` respond to `:to_i` you can you the regular setter without manually converting... just need to add a wrapper to read back as Time/DateTime if necessary. 

```
r.start_seconds = Time.now  #=> 2017-03-08 19:01:31 -0700
r.start_seconds                      #=> 1489024891
r.start_time                             #=> 2017-03-08 19:01:31 -0700
```

**Comment by awood45** [comment]
Related to that, we also now have a built-in `epoch_time_attr` type. In any case, Smart Query is on the feature request backlog, closing.

**Comment by thomaswitt** [comment]
@awood45 Just as a comment, I would appreciate a "smart query" function, in case that means automatic conversion to datetime.

When I e.g. want to sort by updated_at in a secondary index, I always have to write some glue code:
```
  epoch_time_attr :created_at_epoch
  epoch_time_attr :updated_at_epoch

  global_secondary_index(:updated_at_gsi,
                         hash_key: :hk,
                         range_key: :updated_at_epoch,
                         projection: { projection_type: 'ALL' })


  def created_at(tz = Time.zone)
    dt = Time.at(self.created_at_epoch)
    dt.in_time_zone(tz)
  end

  def created_at=(datetime)
    self.created_at_epoch = datetime.to_time.to_i if datetime.present?
  end

  def updated_at(tz = Time.zone)
    dt = Time.at(self.updated_at_epoch)
    dt.in_time_zone(tz)
  end

  def updated_at=(datetime)
    self.updated_at_epoch = datetime.to_time.to_i if datetime.present?
  end
```

In an ideal world, these getter/setter methods would be already built in.
